---
abstract: 'Case insensitive head1 POD matching for the Name attribute'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  Test::Requires: 0.06
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-AbstractFromPOD
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Dist::Zilla::Plugin::AbstractFromPOD:
    file: lib/Dist/Zilla/Plugin/AbstractFromPOD.pm
    version: v0.2.1
requires:
  Dist::Zilla: 5.006
  Moose: 2.0802
  perl: 5.008
  version: 0.88
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Zilla-Plugin-AbstractFromPOD
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.2.1
